transactions.sets.path=src/main/resources/transactionSets.csv
server.executable.path=server/target/server-1.0-SNAPSHOT-jar-with-dependencies.jar
server.cluster.count=3
server.cluster.size=3
database.size=9000
server.port.start=3000
client.port=4000
client.timeout.millis=2000
server.timeout.millis=500
checkpoint.interval=100