syntax = "proto3";

import "google/protobuf/empty.proto";

package org.example;

option java_package = "org.example";
option java_multiple_files = true;

service CLIService {
  rpc SetActiveFlag (ActiveFlag) returns (Acknowledgement) {};
  rpc Reset(google.protobuf.Empty) returns (Acknowledgement) {};

  rpc FailNode(NodeId) returns (Acknowledgement);
  rpc RecoverNode(NodeId) returns (Acknowledgement);

  rpc GetLog(google.protobuf.Empty) returns (CLIResponse) {};
  rpc GetDB(google.protobuf.Empty) returns (CLIResponse) {};
  rpc GetRequests(google.protobuf.Empty) returns (CLIResponse) {};
  rpc GetNewViews(google.protobuf.Empty) returns (CLIResponse) {};

  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty) {};
}

message ActiveFlag {
  bool active_flag = 1;
}

message Acknowledgement {
  bool status = 1;
}

message SequenceNumber {
  int64 sequence_number = 1;
}

message CLIResponse {
  string cli_response = 1;
}

message NodeId {
  int32 node_id = 1;
}