syntax = "proto3";

import "google/protobuf/empty.proto";

package org.example;

option java_package = "org.example";
option java_multiple_files = true;

// Service definition
service ClientService {
  rpc Request(ClientRequest) returns (google.protobuf.Empty) {};
  rpc Reply(ClientReply) returns (google.protobuf.Empty) {};

  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty) {};
}

// Core operation definitions
message Transfer {
  int32 sender = 1;
  int32 receiver = 2;
  double amount = 3;
}

message BalanceRequest {
  int32 account_id = 1;
}

message Operation {
  oneof op {
    Transfer transfer = 1;
    BalanceRequest balance_request = 2;
  }
}

message OperationResult {
  oneof result {
    bool success = 1;
    double balance = 2;
  }
}

// Client-Server communication
message ClientRequest {
  int64 timestamp = 1;
  Operation operation = 2;
  int32 client_id = 3;
  bool is_read_only = 4;
  string request_id = 5;
}

message ClientReply {
  int32 sender_id = 1;
  OperationResult result = 2;
  string request_id = 3;
}
